[engine]
# 确保Podman构建和拉取镜像时不使用本地代理
no_proxy = "localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,.local"

[engine.runtimes]
  [engine.runtimes.runc]
    runtime_path = ""
    [engine.runtimes.runc.options]
      SystemdCgroup = true

[netavark.network.subnets]
  # 定义网络子网以避免与代理冲突
  # 保留子网范围以避免与本地网络冲突
  subnet = "10.89.0.0/16"