# pyright: reportAttributeAccessIssue=false, reportArgumentType=false, reportOptionalMemberAccess=false, reportCallIssue=false, reportGeneralTypeIssues=false, reportMissingImports=false, reportRedeclaration=false, reportFunctionMemberAccess=false, reportPossiblyUnboundVariable=false, reportReturnType=false

"""Helpers for parsing unstructured exon-level CNV descriptions.

The parser searches evidence quotes or markdown generated by the agent for
phrases such as "exons 2-10 deletion" and synthesizes a temporary HGVS-like
descriptor so downstream validation logic can continue.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


EXON_RANGE_PATTERN = re.compile(
	 r"exons?\s*(\d+)(?:\s*(?:-|to)\s*(\d+))?",
	 flags=re.IGNORECASE,
)


STRUCTURAL_KEYWORDS: Dict[str, Sequence[str]] = {
	"DELETION": ("deletion", "deleted", "loss", "del", "缺失"),
	"DUPPLICATION": ("duplication", "duplicated", "dup", "gain", "增多", "扩增"),
	"CNV": ("cnv", "copy number", "copy-number", "copy number variation"),
}


WINDOW_RADIUS = 80
MAX_TEXT_LENGTH = 20000


@dataclass
class StructuralVariantParseResult:
	transcript_id: str
	exon_range: str
	structural_type: str
	source: str
	text_window: str
	synthetic_hgvs: str
	confidence: float = 0.6

	def to_payload(self) -> Dict[str, Any]:
		return {
			"transcript_id": self.transcript_id,
			"exon_range": self.exon_range,
			"structural_type": self.structural_type,
			"synthetic_hgvs": self.synthetic_hgvs,
			"source": self.source,
			"text_window": self.text_window,
			"confidence": self.confidence,
			"structural_key": build_structural_key(
				self.transcript_id, self.exon_range, self.structural_type
			),
		}


def parse_structural_variant(
	evidence_output: Dict[str, Any],
	transcript_id: Optional[str],
	disease_name: Optional[str] = None,
) -> Optional[StructuralVariantParseResult]:
	"""Extract structural variant hints from free text when HGVS is missing."""
	if not transcript_id or not disease_name:
		return None

	for source, text in _iter_candidate_texts(evidence_output):
		match = _find_structural_span(text)
		if not match:
			continue
		start, end, exon_range = match
		snippet = text[max(0, start - WINDOW_RADIUS) : min(len(text), end + WINDOW_RADIUS)]
		structural_type = _infer_structural_type(snippet, text)
		if not structural_type:
			continue
		hgvs = build_structural_hgvs(transcript_id, exon_range, structural_type)
		return StructuralVariantParseResult(
			transcript_id=transcript_id,
			exon_range=exon_range,
			structural_type=structural_type,
			source=source,
			text_window=snippet.strip(),
			synthetic_hgvs=hgvs,
		)
	return None


def build_structural_hgvs(transcript_id: str, exon_range: str, structural_type: str) -> str:
	clean_transcript = transcript_id.strip()
	clean_exon = exon_range.replace(" ", "").replace("_", "-")
	suffix = {
		"DELETION": "del",
		"DUPPLICATION": "dup",
		"CNV": "cnv",
	}.get(structural_type.upper(), structural_type.lower())
	return f"{clean_transcript}:c.(?_?){suffix}(exon{clean_exon})"


def build_structural_key(transcript_id: str, exon_range: Optional[str], structural_type: Optional[str]) -> Optional[str]:
	if not transcript_id or not exon_range:
		return None
	stype = (structural_type or "CNV").upper()
	return f"{transcript_id}:{exon_range}:{stype}"


def _find_structural_span(text: str) -> Optional[Tuple[int, int, str]]:
	normalized = _normalize_text(text)
	for match in EXON_RANGE_PATTERN.finditer(normalized):
		exon_start = match.group(1)
		exon_end = match.group(2)
		if not exon_start:
			continue
		if exon_end and exon_end != exon_start:
			exon_range = f"{exon_start}-{exon_end}"
		else:
			exon_range = exon_start
		return match.start(), match.end(), exon_range
	return None


def _infer_structural_type(snippet: str, full_text: str) -> Optional[str]:
	for text in (snippet.lower(), full_text.lower()):
		for stype, keywords in STRUCTURAL_KEYWORDS.items():
			for keyword in keywords:
				if keyword.lower() in text:
					return stype
	return None


def _iter_candidate_texts(evidence_output: Dict[str, Any]) -> Iterable[Tuple[str, str]]:
	texts: List[Tuple[str, str]] = []
	extracted = evidence_output.get("extracted_fields") or {}
	if isinstance(extracted, dict):
		variant = extracted.get("variant") or {}
		if isinstance(variant, dict):
			for key in ("evidence_quote", "raw_text", "description"):
				value = variant.get(key)
				text = _coerce_text(value)
				if text:
					texts.append((f"extracted.variant.{key}", text))
		transcript = extracted.get("transcript_id") or {}
		if isinstance(transcript, dict):
			text = _coerce_text(transcript.get("evidence_quote"))
			if text:
				texts.append(("extracted.transcript.evidence_quote", text))

	for field in ("origin_format_md", "en_format_md"):
		text = _coerce_text(evidence_output.get(field))
		if text:
			texts.append((field, text))

	ps3_payload = evidence_output.get("ps3_evidence")
	if isinstance(ps3_payload, dict):
		for inner_key, inner_text in _flatten_ps3_text(ps3_payload):
			texts.append((f"ps3.{inner_key}", inner_text))

	seen: set[str] = set()
	for source, text in texts:
		clean = text.strip()
		if not clean:
			continue
		fingerprint = (source, clean[:200])
		if fingerprint in seen:
			continue
		seen.add(fingerprint)
		yield source, clean[:MAX_TEXT_LENGTH]


def _coerce_text(value: Any) -> Optional[str]:
	if isinstance(value, str):
		return value
	if isinstance(value, list):
		parts = [str(item) for item in value if isinstance(item, (str, int, float))]
		if parts:
			return " ".join(parts)
	return None


def _flatten_ps3_text(payload: Dict[str, Any]) -> Iterable[Tuple[str, str]]:
	for key, value in payload.items():
		if isinstance(value, dict):
			for nested_key in ("notes", "summary", "extracted_text"):
				text = value.get(nested_key)
				coerced = _coerce_text(text)
				if coerced:
					yield f"{key}.{nested_key}", coerced
			continue
		coerced = _coerce_text(value)
		if coerced:
			yield key, coerced


def _normalize_text(text: str) -> str:
	transformed = (
		text.replace("外显子", "exon")
		.replace("～", "-")
		.replace("–", "-")
		.replace("—", "-")
		.replace("至", "-")
	)
	return transformed

