"""initial_schema

Revision ID: 4ce26825046c
Revises: review_chat_20260528
Create Date: 2026-05-30 05:07:08.228223+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ce26825046c'
down_revision: Union[str, None] = 'review_chat_20260528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run_states',
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.source_document_id'], ),
    sa.PrimaryKeyConstraint('processing_run_id')
    )
    op.create_index('ix_pipeline_run_states_source_document_id', 'pipeline_run_states', ['source_document_id'], unique=False)
    # NOTE: alembic_version table is managed by alembic itself, not autogenerate.
    # The following were false positives from autogenerate comparing ORM models
    # against the live DB — skipped intentionally:
    #   - op.drop_table('alembic_version')
    #   - ix_terminology_embeddings_embedding_hnsw recreation
    #   - fk_terminology_embeddings_entry_id recreation
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_run_states_source_document_id', table_name='pipeline_run_states')
    op.drop_table('pipeline_run_states')
    # ### end Alembic commands ###
